services:
  web:
    build: docker/web
    container_name: casts_web
    links:
      - mariadb
    depends_on:
      - mariadb
    volumes:
      - ".:/app"
      - "./docker/web/apache2.conf:/etc/apache2/apache2.conf"
      - "./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf"
      - "./docker/web/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini"
    ports:
      - "80:80"

  mariadb:
    image: "mariadb:10.6.7"
    container_name: casts_db
    restart: always
    working_dir: /app
    volumes:
      - ".:/app"
      - "./docker/mariadb/docker-entrypoint-initdb/:/docker-entrypoint-initdb.d:ro"
      - "./docker/mariadb/data:/var/lib/mysql"
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: casts_db
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
    ports:
      - "3306:3306"
